export const highFrequencyErrors = [
  "stray ‘(.+?)’ in program",
  "unknown type name ‘(.+?)’",
  "(undeclared)|(was not declared)|(has not been declared)",
  "(expected (.*) before (.*)|(expected (.*) at end of (.*))|(expected (.*) after (.*)))",
  "too few arguments to function ‘(.+?)’",
  "too many arguments to function ‘(.+?)’",
  "expected declaration specifiers",
  "‘(.+?)’ does not name a type",
  "‘(.+?)’ has no member named ‘(.+?)’",
  "没有那个文件或目录",
  "variably modified ‘(.+?)’ at file scope",
  "redeclaration of ‘(.+?)’",
  "redefinition of ‘(.+?)’",
  "parameter ‘(.+?)’ is initialized",
  "label ‘(.+?)’ used but not defined",
  "conflicting types for ‘(.+?)’",
  "variably modified ‘(.+?)’ at file scope",
  "request for member ‘(.+?)’ in something not a structure or union",
  "array size missing in ‘(.+?)’",
  "no matching function for call to",
  "note:",
]; //高频类似错误合并集

/*
  export const highFrequencyErrors = [
    "stray ‘(.+?)’ in program",
    "unknown type name ‘(.+?)’",
    "‘(.+?)’ undeclared",
    "‘(.+?)’ was not declared",
    "expected ‘(.+?)’ before",
    "expected expression before ‘(.+?)’",
    "expected identifier or ‘(.+?)’ before ‘(.+?)’",
    "too few arguments to function ‘(.+?)’",
    "too many arguments to function ‘(.+?)’",
    "expected identifier before ‘(.+?)’",
    "expected declaration specifiers",
    "‘(.+?)’ does not name a type",
    "‘(.+?)’ has no member named ‘(.+?)’",
    "‘(.+?)’ has not been declared",
    "没有那个文件或目录",
    "variably modified ‘(.+?)’ at file scope",
    "redeclaration of ‘(.+?)’",
    "redefinition of ‘(.+?)’",
    "parameter ‘(.+?)’ is initialized",
    "label ‘(.+?)’ used but not defined",
    "conflicting types for ‘(.+?)’",
    "variably modified ‘(.+?)’ at file scope",
    "expected unqualified-id before ‘(.+?)’",
    "request for member ‘(.+?)’ in something not a structure or union",
    "array size missing in ‘(.+?)’",
    "no matching function for call to",
  ]; //高频类似错误合并集
  */
